import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("teacher dashboard syncs stored config without creating teacher student cards", async () => {
  const worker = await readFile("src/worker.js", "utf8");
  const teacher = await readFile("src/ui/teacher.js", "utf8");

  assert.match(worker, /const config = await this\.state\.storage\.get\("config"\) \|\| null/);
  assert.match(worker, /type: "teacher_config_updated"/);
  assert.match(worker, /const updatedAt = new Date\(\)\.toISOString\(\)/);
  assert.match(worker, /async updateConfig\(data, roomId = "default-classroom"\)/);
  assert.match(worker, /sanitizeTeacherConfig\(data, \{\}\)/);
  assert.match(worker, /type: "teacher_config_rejected"/);
  assert.match(worker, /unsafe_persona_instruction/);
  assert.match(worker, /recordTeacherConfigRejection/);
  assert.match(worker, /buildTeacherConfigRejectedEvent/);
  assert.match(worker, /blockedPattern/);
  assert.match(worker, /findUnsafePersonaInstruction/);
  assert.match(worker, /await this\.updateConfig\(data, normalizeRoomId\(url\.searchParams\.get\("room"\)\)\)/);
  assert.match(worker, /url\.pathname === "\/config" && request\.method === "POST"[\s\S]*this\.updateConfig\(await request\.json\(\), normalizeRoomId\(url\.searchParams\.get\("room"\)\)\)/);
  assert.match(worker, /const config = \{\s*level: nextLevel,\s*persona: nextPersona,\s*responseMode: nextResponseMode,\s*mixLevels: nextMixLevels,\s*falseDensity: nextFalseDensity,\s*updatedAt\s*\}/s);
  assert.match(worker, /const recordedEvent = await this\.recordEvent\(event\)/);
  assert.match(worker, /this\.broadcast\(recordedEvent\)/);
  assert.match(worker, /eventId: event\.eventId \|\| crypto\.randomUUID\(\)/);

  assert.equal(teacher.includes('updateSocketStatus("online");\n        sendTeacherConfig();'), false);
  assert.match(teacher, /if \(event\.config\) applyTeacherConfig\(event\.config\)/);
  assert.match(teacher, /if \(event\.type === "teacher_config_updated"\)[\s\S]*return;/);
  assert.match(teacher, /if \(event\.type === "teacher_config_rejected"\)[\s\S]*return;/);
  assert.match(teacher, /if \(telemetry\.type !== "snapshot"\) liveTelemetrySinceConnect = true/);
  assert.match(teacher, /const seenEventIds = new Set\(\)/);
  assert.match(teacher, /if \(seenEventIds\.has\(event\.eventId\)\) return/);
  assert.match(teacher, /seenEventIds\.add\(event\.eventId\)/);
  assert.match(teacher, /if \(event\.type === "snapshot"\)[\s\S]*if \(!liveTelemetrySinceConnect\) \{[\s\S]*sessions\.clear\(\);[\s\S]*selected = null;[\s\S]*for \(const item of event\.events \|\| \[\]\) handleTelemetry\(item\);[\s\S]*if \(previousSelected && sessions\.has\(previousSelected\)\) selected = previousSelected;[\s\S]*return;/);
  assert.match(teacher, /if \(event\.type === "events_purged"\)[\s\S]*sessions\.clear\(\);[\s\S]*selected = null;[\s\S]*renderEmptyChat\("촬영 로그가 삭제되었습니다\."\);[\s\S]*return;/);
  assert.match(teacher, /function applyTeacherConfig\(config\)/);
  assert.match(teacher, /async function sendTeacherConfig\(\)/);
  assert.match(teacher, /await postTeacherConfig\(payload\)/);
  assert.match(teacher, /async function postTeacherConfig\(payload\)/);
  assert.match(teacher, /fetch\(withRoom\("\/api\/config"\)/);
  assert.match(teacher, /저장 실패: /);
  assert.match(teacher, /저장 실패: 네트워크 확인/);
  assert.match(teacher, /id="configStatus"/);
  assert.match(teacher, /id="socketStatus"[^>]+aria-live="polite"/);
  assert.match(teacher, /configStatusEl\.value = "저장 중/);
  assert.match(teacher, /configStatusEl\.value = "적용됨/);
  assert.match(teacher, /id="classSummary"/);
  assert.match(teacher, /function renderClassSummary/);
  assert.match(teacher, /classSummaryEl\.replaceChildren/);
  assert.match(teacher, /function summaryMetric\(label, value\)/);
  assert.match(teacher, /strong\.textContent = String\(value\)/);
  assert.match(teacher, /current\.chatTurns = \(current\.chatTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /current\.blockedTurns = \(current\.blockedTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /current\.debriefRequiredTurns = \(current\.debriefRequiredTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /history\.replaceState/);
  assert.match(teacher, /encodeTeacherWebSocketProtocol\(teacherToken\)/);
  assert.match(teacher, /new WebSocket\([^,]+, protocols\)/);
  assert.doesNotMatch(teacher, /query\.set\("token", teacherToken\)/);
  assert.match(teacher, /function buildRoomUrl\(path, includeToken = false\)/);
  assert.match(teacher, /function exportFilename\(kind, extension\)/);
  assert.match(teacher, /roomId \+ "-" \+ kind/);
  assert.match(teacher, /current\.latencyMs = event\.latencyMs/);
  assert.match(teacher, /current\.lastQuestion = event\.studentMessage/);
  assert.match(teacher, /current\.blockedForStudent = Boolean\(event\.blockedForStudent\)/);
  assert.match(teacher, /blockedTurns \+= session\.blockedTurns \|\| 0/);
  assert.match(teacher, /debriefRequiredTurns \+= session\.debriefRequiredTurns \|\| 0/);
  assert.match(teacher, /summaryMetric\("차단턴", blockedTurns\)/);
  assert.match(teacher, /summaryMetric\("사후정정", debriefRequiredTurns\)/);
  assert.match(teacher, /blocked\.textContent = session\.blockedTurns \? "blocked " \+ session\.blockedTurns : "blocked"/);
  assert.match(teacher, /debrief\.textContent = "정정 " \+ session\.debriefRequiredTurns/);
  assert.match(teacher, /document\.createTextNode\(session\.name\)/);
  assert.doesNotMatch(teacher, /\.innerHTML/);
  assert.match(teacher, /studentsEl\.replaceChildren\(\)/);
  assert.match(teacher, /chatEl\.replaceChildren\(\)/);
  assert.match(teacher, /function renderEmptyChat\(message\)/);
  assert.match(teacher, /blockedMsg/);
  assert.match(teacher, /session\.latencyMs/);
  assert.match(teacher, /질문: " \+ trimCardText\(session\.lastQuestion\)/);
  assert.match(teacher, /function trimCardText\(value\)/);
  assert.match(teacher, /text\.length > 34/);
  assert.match(teacher, /copyStudentUrlEl\.addEventListener/);
  assert.match(teacher, /copyTeacherUrlEl\.addEventListener/);
  assert.match(teacher, /id="copyAuditJson"/);
  assert.match(teacher, /copyAuditJsonEl\.addEventListener\("click", \(\) => copyText\(auditEl\.textContent, "audit json"\)\)/);
  assert.match(teacher, /네트워크 문제로 다운로드하지 못했습니다/);
  assert.match(teacher, /네트워크 문제로 촬영 로그를 삭제하지 못했습니다/);
  assert.match(teacher, /className = "studentDelete"/);
  assert.match(teacher, /deleteButton\.textContent = "×"/);
  assert.match(teacher, /event\.stopPropagation\(\)/);
  assert.match(teacher, /async function deleteStudent\(sessionId, studentName\)/);
  assert.match(teacher, /method: "DELETE"/);
  assert.match(teacher, /event\.type === "student_deleted"/);
  assert.match(teacher, /답변의 말투·역할·설명 방식만 정합니다/);
  assert.match(teacher, /진실\/실험 모드, 거짓 Level, 교사용 정답·검수 규칙은 변경하거나 학생에게 공개할 수 없습니다/);
  assert.match(teacher, /Powered by NomaDamas/);
  assert.match(teacher, /id="dashboardSettings"/);
  assert.match(teacher, /수업 운영 설정 · 응답 모드, Level, 연결 상태, 페르소나/);
  assert.match(teacher, /id="savePersona"[^>]*>페르소나 저장/);
  assert.match(teacher, /savePersonaEl\.addEventListener\("click", sendTeacherConfig\)/);
  assert.doesNotMatch(teacher, /personaEl\.addEventListener\("change", sendTeacherConfig\)/);
  assert.match(teacher, /수업 기본값/);
  assert.match(teacher, /진실\+거짓 혼합/);
  assert.match(teacher, /반 전체 기본 응답 설정/);
  assert.match(teacher, /왼쪽 학생 카드에서 개별 모드를 선택하면 해당 학생에게만 이 기본값을 덮어씁니다/);
  assert.match(teacher, /학생별 응답 설정/);
  assert.match(teacher, /className = "studentConfigFields"/);
  assert.match(teacher, /document\.createTextNode\("응답 모드"\)/);
  assert.match(teacher, /document\.createTextNode\("거짓 Level"\)/);
  assert.match(teacher, /async function updateStudentConfig\(sessionId, responseMode, level, falseDensity\)/);
  assert.match(teacher, /fetch\(withRoom\("\/api\/student-config"\)/);
  assert.match(teacher, /event\.type === "student_config_updated"/);
  assert.match(teacher, /id="studentSearch"/);
  assert.match(teacher, /id="studentSearchInput" type="search"/);
  assert.match(teacher, />검색하기<\/button>/);
  assert.match(teacher, /studentSearchEl\.addEventListener\("submit"/);
  assert.match(teacher, /normalizedName\.includes\(studentSearchQuery\)/);
  assert.match(teacher, /studentSearchInputEl\.addEventListener\("input"/);
});

test("teacher dashboard preserves response mode and separates teacher-only review evidence", async () => {
  const teacher = await readFile("src/ui/teacher.js", "utf8");

  assert.match(teacher, /id="responseMode" aria-describedby="responseModeHelp"/);
  assert.match(teacher, /option value="experiment" selected>실험 · 진실\+거짓/);
  assert.match(teacher, /option value="truth">진실 · 검수 사실만/);
  assert.match(teacher, /option value="mixed">혼합 · 진실\/복수 Level/);
  assert.match(teacher, /responseMode: responseModeEl\.value/);
  assert.match(teacher, /body: JSON\.stringify\(\{\s*responseMode: payload\.responseMode,\s*level: payload\.level,\s*mixLevels: payload\.mixLevels,\s*falseDensity: payload\.falseDensity,\s*persona: payload\.persona\s*\}\)/s);
  assert.match(teacher, /\["experiment", "truth", "mixed"\]\.includes\(config\.responseMode\)/);
  assert.match(teacher, /responseModeEl\.value = config\.responseMode/);
  assert.match(teacher, /적용됨: " \+ appliedMode/);
  assert.match(teacher, /responseModeEl\.addEventListener\("change"/);

  assert.match(teacher, /function updateResponseModeUi\(\)/);
  assert.match(teacher, /const truthMode = responseModeEl\.value === "truth"/);
  assert.match(teacher, /levelEl\.disabled = truthMode \|\| mixedMode/);
  assert.match(teacher, /levelEl\.setAttribute\("aria-disabled", String\(truthMode \|\| mixedMode\)\)/);
  assert.match(teacher, /selectedMixLevels/);
  assert.match(teacher, /혼합 모드는 2개 이상 선택/);
  assert.match(teacher, /진실 모드에서는 Level을 적용하지 않습니다/);
  assert.match(teacher, /event\.teacherAudit\?\.input\?\.appliedLevel/);

  assert.match(teacher, /id="teacherReviewTitle">교사용 검수 영역/);
  assert.match(teacher, /교사 전용 · 학생 비노출/);
  assert.match(teacher, /학생에게 보인 대화/);
  assert.match(teacher, /function renderTeacherReview\(audit, blockedForStudent = false\)/);
  assert.match(teacher, /정답 · 교사 기준/);
  assert.match(teacher, /거짓 · 학생용 생성안/);
  assert.match(teacher, /왜 거짓인가/);
  assert.match(teacher, /Level·거짓 밀도/);
  assert.match(teacher, /검수 결과/);
  assert.match(teacher, /truth 모드는 거짓 정보를 생성하거나 노출하지 않음/);
  assert.match(teacher, /body\.textContent = value \|\| "정보 없음"/);
  assert.match(teacher, /원시 감사 JSON 보기/);
  assert.match(teacher, /class="auditDetails"/);
  assert.match(teacher, /\.reviewPanel \{ display: grid; grid-template-rows: auto minmax\(0, 1fr\) auto; \}/);
  assert.match(teacher, /\.auditDetails\[open\] \{ max-height: 240px; overflow: auto; \}/);

  assert.match(teacher, /최대 35명/);
  assert.match(teacher, /#students \{[\s\S]*overflow-y: auto/);
  assert.match(teacher, /@media \(max-width: 1080px\)/);
  assert.match(teacher, /el\.setAttribute\("role", "button"\)/);
  assert.match(teacher, /event\.key !== "Enter" && event\.key !== " "/);
  assert.match(teacher, /id="teacherReviewContext" aria-live="polite"/);
  assert.match(teacher, /id="latestTurnButton"/);
});

test("teacher dashboard prioritizes 35-student live telemetry and audits each conversation turn", async () => {
  const teacher = await readFile("src/ui/teacher.js", "utf8");

  assert.match(teacher, /data-filter="all" aria-pressed="true">전체/);
  assert.match(teacher, /data-filter="online" aria-pressed="false">온라인/);
  assert.match(teacher, /data-filter="attention" aria-pressed="false">주의 필요/);
  assert.match(teacher, /\.sort\(compareStudentPriority\)/);
  assert.match(teacher, /function studentMatchesFilter\(session\)/);
  assert.match(teacher, /function compareStudentPriority\(\[, left\], \[, right\]\)/);
  assert.match(teacher, /leftAttention !== rightAttention/);
  assert.match(teacher, /function telemetryAgeLabel\(lastSeenMs\)/);
  assert.match(teacher, /seconds \+ "초 전"/);
  assert.match(teacher, /session\.responseMode === "truth"[\s\S]*truth · Level 비적용/);
  assert.match(teacher, /current\.appliedLevel = event\.teacherAudit\?\.input\?\.appliedLevel/);
  assert.match(teacher, /truth · Level 비적용/);
  assert.match(teacher, /experiment · Level /);
  assert.match(teacher, /document\.activeElement\?\.dataset\?\.sessionId/);
  assert.match(teacher, /focusedCard\?\.focus\(\{ preventScroll: true \}\)/);
  assert.match(teacher, /studentFilterEls\.forEach/);

  assert.match(teacher, /audit: event\.teacherAudit/);
  assert.match(teacher, /audit: event\.teacherAudit,\s*turn/);
  assert.match(teacher, /function groupMessagesByTurn\(messages\)/);
  assert.match(teacher, /function findReviewMessage\(session\)/);
  assert.match(teacher, /reviewButton\.textContent = message\.blockedForStudent \? "차단된 턴 검수" : "이 턴 검수"/);
  assert.match(teacher, /selectedTurn = message\.turn/);
  assert.match(teacher, /renderTeacherReview\(selectedAudit/);
  assert.match(teacher, /auditEl\.textContent = selectedAudit \? JSON\.stringify\(selectedAudit/);
  assert.match(teacher, /if \(selected === event\.sessionId\) \{[\s\S]*renderSelected\(\)/);
  assert.match(teacher, /chatEl\.scrollTop = chatEl\.scrollHeight/);
  assert.match(teacher, /teacherReviewContextEl\.textContent = session\.name/);
  assert.match(teacher, /let processingSnapshot = false/);
  assert.match(teacher, /processingSnapshot = true/);
  assert.match(teacher, /if \(processingSnapshot\) return/);
  assert.match(teacher, /let reviewPinned = false/);
  assert.match(teacher, /event\.type === "chat_turn" && reviewPinned/);
  assert.match(teacher, /latestTurnButtonEl\.classList\.remove\("hidden"\)/);
  assert.match(teacher, /right\.lastChatAtMs/);
  assert.match(teacher, /id="conversationPanel"/);
  assert.match(teacher, /id="reviewPanel"/);
  assert.match(teacher, /window\.matchMedia\("\(max-width: 900px\)"\)\.matches/);
  assert.match(teacher, /conversationPanelEl\.scrollIntoView/);
  assert.match(teacher, /reviewPanelEl\.scrollIntoView/);
});
