import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("teacher dashboard syncs stored config without creating teacher student cards", async () => {
  const worker = await readFile("src/worker.js", "utf8");
  const teacher = await readFile("src/ui/teacher.js", "utf8");

  assert.match(worker, /const config = await this\.state\.storage\.get\("config"\) \|\| null/);
  assert.match(worker, /type: "teacher_config_updated"/);
  assert.match(worker, /const updatedAt = new Date\(\)\.toISOString\(\)/);
  assert.match(worker, /async updateConfig\(data, roomId = "default-classroom"\)/);
  assert.match(worker, /sanitizeTeacherConfig\(data, \{\}\)/);
  assert.match(worker, /type: "teacher_config_rejected"/);
  assert.match(worker, /unsafe_persona_instruction/);
  assert.match(worker, /recordTeacherConfigRejection/);
  assert.match(worker, /buildTeacherConfigRejectedEvent/);
  assert.match(worker, /blockedPattern/);
  assert.match(worker, /findUnsafePersonaInstruction/);
  assert.match(worker, /await this\.updateConfig\(data, normalizeRoomId\(url\.searchParams\.get\("room"\)\)\)/);
  assert.match(worker, /url\.pathname === "\/config" && request\.method === "POST"[\s\S]*this\.updateConfig\(await request\.json\(\), normalizeRoomId\(url\.searchParams\.get\("room"\)\)\)/);
  assert.match(worker, /const config = \{\s*level: nextLevel,\s*persona: nextPersona,\s*updatedAt\s*\}/s);
  assert.match(worker, /const recordedEvent = await this\.recordEvent\(event\)/);
  assert.match(worker, /this\.broadcast\(recordedEvent\)/);

  assert.equal(teacher.includes('updateSocketStatus("online");\n        sendTeacherConfig();'), false);
  assert.match(teacher, /if \(event\.config\) applyTeacherConfig\(event\.config\)/);
  assert.match(teacher, /if \(event\.type === "teacher_config_updated"\)[\s\S]*return;/);
  assert.match(teacher, /if \(event\.type === "teacher_config_rejected"\)[\s\S]*return;/);
  assert.match(teacher, /if \(event\.type === "snapshot"\)[\s\S]*sessions\.clear\(\);[\s\S]*selected = null;[\s\S]*for \(const item of event\.events \|\| \[\]\) handleTelemetry\(item\);[\s\S]*if \(previousSelected && sessions\.has\(previousSelected\)\) selected = previousSelected;[\s\S]*return;/);
  assert.match(teacher, /if \(event\.type === "events_purged"\)[\s\S]*sessions\.clear\(\);[\s\S]*selected = null;[\s\S]*renderEmptyChat\("촬영 로그가 삭제되었습니다\."\);[\s\S]*return;/);
  assert.match(teacher, /function applyTeacherConfig\(config\)/);
  assert.match(teacher, /async function sendTeacherConfig\(\)/);
  assert.match(teacher, /await postTeacherConfig\(payload\)/);
  assert.match(teacher, /async function postTeacherConfig\(payload\)/);
  assert.match(teacher, /fetch\(withRoom\("\/api\/config"\)/);
  assert.match(teacher, /저장 실패: /);
  assert.match(teacher, /저장 실패: 네트워크 확인/);
  assert.match(teacher, /id="configStatus"/);
  assert.match(teacher, /configStatusEl\.value = "저장 중/);
  assert.match(teacher, /configStatusEl\.value = "적용됨/);
  assert.match(teacher, /id="classSummary"/);
  assert.match(teacher, /function renderClassSummary/);
  assert.match(teacher, /classSummaryEl\.replaceChildren/);
  assert.match(teacher, /function summaryMetric\(label, value\)/);
  assert.match(teacher, /strong\.textContent = String\(value\)/);
  assert.match(teacher, /current\.chatTurns = \(current\.chatTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /current\.blockedTurns = \(current\.blockedTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /current\.debriefRequiredTurns = \(current\.debriefRequiredTurns \|\| 0\) \+ 1/);
  assert.match(teacher, /history\.replaceState/);
  assert.match(teacher, /encodeTeacherWebSocketProtocol\(teacherToken\)/);
  assert.match(teacher, /new WebSocket\([^,]+, protocols\)/);
  assert.doesNotMatch(teacher, /query\.set\("token", teacherToken\)/);
  assert.match(teacher, /function buildRoomUrl\(path, includeToken = false\)/);
  assert.match(teacher, /function exportFilename\(kind, extension\)/);
  assert.match(teacher, /roomId \+ "-" \+ kind/);
  assert.match(teacher, /current\.latencyMs = event\.latencyMs/);
  assert.match(teacher, /current\.lastQuestion = event\.studentMessage/);
  assert.match(teacher, /current\.blockedForStudent = Boolean\(event\.blockedForStudent\)/);
  assert.match(teacher, /blockedTurns \+= session\.blockedTurns \|\| 0/);
  assert.match(teacher, /debriefRequiredTurns \+= session\.debriefRequiredTurns \|\| 0/);
  assert.match(teacher, /summaryMetric\("차단턴", blockedTurns\)/);
  assert.match(teacher, /summaryMetric\("정정필요", debriefRequiredTurns\)/);
  assert.match(teacher, /blocked\.textContent = session\.blockedTurns \? "blocked " \+ session\.blockedTurns : "blocked"/);
  assert.match(teacher, /debrief\.textContent = "정정 " \+ session\.debriefRequiredTurns/);
  assert.match(teacher, /document\.createTextNode\(session\.name\)/);
  assert.doesNotMatch(teacher, /\.innerHTML/);
  assert.match(teacher, /studentsEl\.replaceChildren\(\)/);
  assert.match(teacher, /chatEl\.replaceChildren\(\)/);
  assert.match(teacher, /function renderEmptyChat\(message\)/);
  assert.match(teacher, /blockedMsg/);
  assert.match(teacher, /session\.latencyMs/);
  assert.match(teacher, /질문: " \+ trimCardText\(session\.lastQuestion\)/);
  assert.match(teacher, /function trimCardText\(value\)/);
  assert.match(teacher, /text\.length > 34/);
  assert.match(teacher, /copyStudentUrlEl\.addEventListener/);
  assert.match(teacher, /copyTeacherUrlEl\.addEventListener/);
  assert.match(teacher, /id="copyAuditJson"/);
  assert.match(teacher, /copyAuditJsonEl\.addEventListener\("click", \(\) => copyText\(auditEl\.textContent, "audit json"\)\)/);
  assert.match(teacher, /네트워크 문제로 다운로드하지 못했습니다/);
  assert.match(teacher, /네트워크 문제로 촬영 로그를 삭제하지 못했습니다/);
});
