import { readFileSync } from "node:fs";

const failures = [];

const externalReviewDecision = normalizeDecision(process.env.EXTERNAL_REVIEW_DECISION);
const verifyDeployStatus = normalizeStatus(process.env.VERIFY_DEPLOY_STATUS);
const workerUrl = String(process.env.WORKER_URL || process.env.WORKER_HEALTH_URL || "").trim();
const prHeadSha = String(process.env.PR_HEAD_SHA || process.env.GITHUB_SHA || "").trim();
const expectedHeadSha = String(process.env.EXPECTED_PR_HEAD_SHA || "").trim();
const ciStatus = normalizeStatus(process.env.CI_STATUS || process.env.GITHUB_CI_STATUS);
const requireOpenAI = process.env.REQUIRE_OPENAI !== "false";
const requireTeacherToken = process.env.REQUIRE_TEACHER_TOKEN !== "false";
const requireClassroomConfig = process.env.REQUIRE_CLASSROOM_CONFIG !== "false";
const externalReviewFile = String(process.env.EXTERNAL_REVIEW_FILE || "").trim();
const verifyDeployEvidenceFile = String(process.env.VERIFY_DEPLOY_EVIDENCE_FILE || "").trim();
const classroomConfigEvidenceFile = String(process.env.CLASSROOM_CONFIG_EVIDENCE_FILE || "").trim();
const classroomConfigEvidenceFiles = parseEvidenceFileList(process.env.CLASSROOM_CONFIG_EVIDENCE_FILES || classroomConfigEvidenceFile);
const expectedClassroomRooms = parseEvidenceFileList(process.env.EXPECTED_CLASSROOM_ROOMS);

if (externalReviewDecision !== "approve") {
  failures.push("EXTERNAL_REVIEW_DECISION=APPROVE is required before merge/release");
}

if (verifyDeployStatus !== "pass") {
  failures.push("VERIFY_DEPLOY_STATUS=pass is required after running npm run verify:deploy against the real Worker URL");
}

if (!isHttpsUrl(workerUrl)) {
  failures.push("WORKER_URL or WORKER_HEALTH_URL must be the real https Cloudflare Worker URL");
}

if (!prHeadSha) {
  failures.push("PR_HEAD_SHA or GITHUB_SHA is required so review/deploy evidence is tied to a commit");
}

if (expectedHeadSha && prHeadSha && expectedHeadSha !== prHeadSha) {
  failures.push("EXPECTED_PR_HEAD_SHA does not match PR_HEAD_SHA; rerun review/deploy verification on the latest commit");
}

if (ciStatus !== "pass" && ciStatus !== "success") {
  failures.push("CI_STATUS=pass or CI_STATUS=success is required for the latest PR head");
}

if (requireOpenAI && process.env.REQUIRE_OPENAI !== "true") {
  failures.push("REQUIRE_OPENAI=true must be recorded for production release verification");
}

if (requireTeacherToken && process.env.REQUIRE_TEACHER_TOKEN !== "true") {
  failures.push("REQUIRE_TEACHER_TOKEN=true must be recorded for production release verification");
}

if (requireClassroomConfig && process.env.REQUIRE_CLASSROOM_CONFIG !== "true") {
  failures.push("REQUIRE_CLASSROOM_CONFIG=true must be recorded for filming release verification");
}

const externalReview = readJsonEvidence(externalReviewFile, "EXTERNAL_REVIEW_FILE");
if (!externalReviewFile) {
  failures.push("EXTERNAL_REVIEW_FILE is required and must contain the external GPT-5.5 xhigh/equivalent review decision");
} else if (externalReview) {
  if (normalizeDecision(externalReview.decision || externalReview.reviewDecision) !== "approve") {
    failures.push("EXTERNAL_REVIEW_FILE decision must be APPROVE");
  }
  if (!externalReview.prHeadSha || externalReview.prHeadSha !== prHeadSha) {
    failures.push("EXTERNAL_REVIEW_FILE prHeadSha must match PR_HEAD_SHA");
  }
  if (!String(externalReview.reviewer || externalReview.model || "").trim()) {
    failures.push("EXTERNAL_REVIEW_FILE must identify the external reviewer/model");
  }
}

const deployEvidence = readJsonEvidence(verifyDeployEvidenceFile, "VERIFY_DEPLOY_EVIDENCE_FILE");
if (!verifyDeployEvidenceFile) {
  failures.push("VERIFY_DEPLOY_EVIDENCE_FILE is required and must be generated by npm run verify:deploy against the real Worker URL");
} else if (deployEvidence) {
  if (deployEvidence.schemaVersion !== "deploy-verification-evidence/v1") {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE schemaVersion must be deploy-verification-evidence/v1");
  }
  if (normalizeStatus(deployEvidence.status) !== "pass") {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE status must be pass");
  }
  if (!deployEvidence.prHeadSha || deployEvidence.prHeadSha !== prHeadSha) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE prHeadSha must match PR_HEAD_SHA");
  }
  if (normalizeBaseUrl(deployEvidence.workerUrl) !== normalizeBaseUrl(workerUrl)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE workerUrl must match WORKER_URL");
  }
  if (deployEvidence.requireOpenAI !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record requireOpenAI=true");
  }
  if (deployEvidence.requireTeacherToken !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record requireTeacherToken=true");
  }
  if (!Number.isFinite(deployEvidence.totalChecks) || deployEvidence.totalChecks < 18) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must include all deploy verification checks");
  }
  if (deployEvidence.passedChecks !== deployEvidence.totalChecks) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE passedChecks must equal totalChecks");
  }
}

if (requireClassroomConfig && classroomConfigEvidenceFiles.length === 0) {
  failures.push("CLASSROOM_CONFIG_EVIDENCE_FILES or CLASSROOM_CONFIG_EVIDENCE_FILE is required and must be generated by npm run rehearsal:config against every filming room");
} else if (classroomConfigEvidenceFiles.length) {
  const seenRooms = new Set();
  for (const file of classroomConfigEvidenceFiles) {
    const classroomConfigEvidence = readJsonEvidence(file, "CLASSROOM_CONFIG_EVIDENCE_FILE");
    if (!classroomConfigEvidence) continue;
    validateClassroomConfigEvidence(classroomConfigEvidence, file, seenRooms);
  }
  if (requireClassroomConfig) validateExpectedClassroomRooms(seenRooms);
}

if (failures.length) {
  for (const failure of failures) console.error(`FAIL ${failure}`);
  console.error(`release audit failed: ${failures.length} issue(s)`);
  process.exit(1);
}

console.log("release audit passed");
console.log(`prHeadSha=${prHeadSha}`);
console.log(`workerUrl=${workerUrl}`);
console.log(`externalReviewDecision=${externalReviewDecision}`);
console.log(`verifyDeployStatus=${verifyDeployStatus}`);
console.log(`externalReviewFile=${externalReviewFile}`);
console.log(`verifyDeployEvidenceFile=${verifyDeployEvidenceFile}`);
console.log(`classroomConfigEvidenceFiles=${classroomConfigEvidenceFiles.join(",")}`);
console.log(`expectedClassroomRooms=${expectedClassroomRooms.join(",")}`);

function normalizeDecision(value) {
  return String(value || "").trim().toLowerCase().replace(/[^a-z_]/g, "");
}

function normalizeStatus(value) {
  return String(value || "").trim().toLowerCase();
}

function isHttpsUrl(value) {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && Boolean(url.hostname);
  } catch {
    return false;
  }
}

function normalizeBaseUrl(value) {
  try {
    const url = new URL(String(value || ""));
    url.pathname = "/";
    url.search = "";
    url.hash = "";
    return url.toString();
  } catch {
    return "";
  }
}

function readJsonEvidence(file, label) {
  if (!file) return null;
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    failures.push(`${label} must be readable JSON: ${error instanceof Error ? error.message : String(error)}`);
    return null;
  }
}

function parseEvidenceFileList(value) {
  return String(value || "")
    .split(/[\n,]+/)
    .map((file) => file.trim())
    .filter(Boolean);
}

function validateClassroomConfigEvidence(classroomConfigEvidence, file, seenRooms) {
  const label = `CLASSROOM_CONFIG_EVIDENCE_FILE ${file}`;
  if (classroomConfigEvidence.schemaVersion !== "classroom-config-evidence/v1") {
    failures.push(`${label} schemaVersion must be classroom-config-evidence/v1`);
  }
  if (normalizeStatus(classroomConfigEvidence.status) !== "pass") {
    failures.push(`${label} status must be pass`);
  }
  if (!classroomConfigEvidence.prHeadSha || classroomConfigEvidence.prHeadSha !== prHeadSha) {
    failures.push(`${label} prHeadSha must match PR_HEAD_SHA`);
  }
  if (normalizeBaseUrl(classroomConfigEvidence.workerUrl) !== normalizeBaseUrl(workerUrl)) {
    failures.push(`${label} workerUrl must match WORKER_URL`);
  }
  if (!isFilmingRoom(classroomConfigEvidence.roomId)) {
    failures.push(`${label} roomId must be a filming/rehearsal room, not default-classroom or deploy-verify`);
  } else if (seenRooms.has(classroomConfigEvidence.roomId)) {
    failures.push(`${label} roomId must be unique across CLASSROOM_CONFIG_EVIDENCE_FILES`);
  } else {
    seenRooms.add(classroomConfigEvidence.roomId);
  }
  if (!Number.isInteger(classroomConfigEvidence.expectedLevel) || classroomConfigEvidence.expectedLevel < 1 || classroomConfigEvidence.expectedLevel > 4) {
    failures.push(`${label} expectedLevel must be 1, 2, 3, or 4`);
  }
  if (!String(classroomConfigEvidence.expectedPersona || "").trim()) {
    failures.push(`${label} expectedPersona is required`);
  }
  if (classroomConfigEvidence.requireOpenAI !== true) {
    failures.push(`${label} must record requireOpenAI=true`);
  }
  if (classroomConfigEvidence.requireTeacherToken !== true) {
    failures.push(`${label} must record requireTeacherToken=true`);
  }
  if (classroomConfigEvidence.observedConfig?.persona !== classroomConfigEvidence.expectedPersona ||
    Number(classroomConfigEvidence.observedConfig?.level) !== classroomConfigEvidence.expectedLevel) {
    failures.push(`${label} observedConfig must match expected Level/persona`);
  }
  if (!Array.isArray(classroomConfigEvidence.checks) || classroomConfigEvidence.checks.some((check) => check?.passed !== true)) {
    failures.push(`${label} checks must all pass`);
  }
}

function validateExpectedClassroomRooms(seenRooms) {
  if (expectedClassroomRooms.length === 0) {
    failures.push("EXPECTED_CLASSROOM_ROOMS is required when REQUIRE_CLASSROOM_CONFIG=true so release audit can prove every filming room has evidence");
    return;
  }
  const expectedRooms = new Set(expectedClassroomRooms.map((room) => normalizeEvidenceRoom(room)));
  for (const room of expectedRooms) {
    if (!isFilmingRoom(room)) {
      failures.push(`EXPECTED_CLASSROOM_ROOMS contains non-filming room ${room}`);
    }
    if (!seenRooms.has(room)) {
      failures.push(`CLASSROOM_CONFIG_EVIDENCE_FILES missing expected filming room ${room}`);
    }
  }
  for (const room of seenRooms) {
    if (!expectedRooms.has(room)) {
      failures.push(`CLASSROOM_CONFIG_EVIDENCE_FILES contains unexpected filming room ${room}`);
    }
  }
}

function normalizeEvidenceRoom(value) {
  return String(value || "").trim();
}

function isFilmingRoom(value) {
  const room = String(value || "").trim();
  return Boolean(room) &&
    room !== "default-classroom" &&
    room !== "deploy-verify" &&
    !room.startsWith("deploy-verify-");
}
