import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";

const failures = [];

const externalReviewDecision = normalizeDecision(process.env.EXTERNAL_REVIEW_DECISION);
const verifyDeployStatus = normalizeStatus(process.env.VERIFY_DEPLOY_STATUS);
const workerUrl = String(process.env.WORKER_URL || process.env.WORKER_HEALTH_URL || "").trim();
const prHeadSha = String(process.env.PR_HEAD_SHA || process.env.GITHUB_SHA || "").trim();
const expectedHeadSha = String(process.env.EXPECTED_PR_HEAD_SHA || "").trim();
const ciStatus = normalizeStatus(process.env.CI_STATUS || process.env.GITHUB_CI_STATUS);
const ciHeadSha = String(process.env.CI_HEAD_SHA || "").trim();
const ciEvidenceFile = String(process.env.CI_EVIDENCE_FILE || "").trim();
const evaluationSetEvidenceFile = String(process.env.EVALUATION_SET_EVIDENCE_FILE || "").trim();
const requireOpenAI = process.env.REQUIRE_OPENAI !== "false";
const requireTeacherToken = process.env.REQUIRE_TEACHER_TOKEN !== "false";
const requireClassroomConfig = process.env.REQUIRE_CLASSROOM_CONFIG !== "false";
const requireCloudflareEdge = process.env.REQUIRE_CLOUDFLARE_EDGE === "true";
const requireClassroomChatProof = process.env.REQUIRE_CLASSROOM_CHAT_PROOF === "true";
const externalReviewFile = String(process.env.EXTERNAL_REVIEW_FILE || "").trim();
const verifyDeployEvidenceFile = String(process.env.VERIFY_DEPLOY_EVIDENCE_FILE || "").trim();
const classroomConfigEvidenceFile = String(process.env.CLASSROOM_CONFIG_EVIDENCE_FILE || "").trim();
const classroomConfigEvidenceFiles = parseEvidenceFileList(process.env.CLASSROOM_CONFIG_EVIDENCE_FILES || classroomConfigEvidenceFile);
const expectedClassroomRooms = parseEvidenceFileList(process.env.EXPECTED_CLASSROOM_ROOMS);

if (externalReviewDecision !== "approve") {
  failures.push("EXTERNAL_REVIEW_DECISION=APPROVE is required before merge/release");
}

if (verifyDeployStatus !== "pass") {
  failures.push("VERIFY_DEPLOY_STATUS=pass is required after running npm run verify:deploy against the real Worker URL");
}

if (!isHttpsUrl(workerUrl)) {
  failures.push("WORKER_URL or WORKER_HEALTH_URL must be the real https Cloudflare Worker URL");
}

if (!prHeadSha) {
  failures.push("PR_HEAD_SHA or GITHUB_SHA is required so review/deploy evidence is tied to a commit");
}

if (expectedHeadSha && prHeadSha && expectedHeadSha !== prHeadSha) {
  failures.push("EXPECTED_PR_HEAD_SHA does not match PR_HEAD_SHA; rerun review/deploy verification on the latest commit");
}

if (ciStatus !== "pass" && ciStatus !== "success") {
  failures.push("CI_STATUS=pass or CI_STATUS=success is required for the latest PR head");
}

if (!ciHeadSha) {
  failures.push("CI_HEAD_SHA is required so CI success is tied to the latest PR head");
} else if (prHeadSha && ciHeadSha !== prHeadSha) {
  failures.push("CI_HEAD_SHA must match PR_HEAD_SHA; rerun CI on the latest PR head");
}

const ciEvidence = readJsonEvidence(ciEvidenceFile, "CI_EVIDENCE_FILE");
let ciEvidenceGeneratedAt = null;
if (!ciEvidenceFile) {
  failures.push("CI_EVIDENCE_FILE is required and must be generated by npm run verify:ci for the latest PR head");
} else if (ciEvidence) {
  if (ciEvidence.schemaVersion !== "ci-evidence/v1") {
    failures.push("CI_EVIDENCE_FILE schemaVersion must be ci-evidence/v1");
  }
  if (normalizeStatus(ciEvidence.status) !== "pass") {
    failures.push("CI_EVIDENCE_FILE status must be pass");
  }
  if (!ciEvidence.prHeadSha || ciEvidence.prHeadSha !== prHeadSha) {
    failures.push("CI_EVIDENCE_FILE prHeadSha must match PR_HEAD_SHA");
  }
  if (ciHeadSha && ciEvidence.prHeadSha !== ciHeadSha) {
    failures.push("CI_EVIDENCE_FILE prHeadSha must match CI_HEAD_SHA");
  }
  ciEvidenceGeneratedAt = parseEvidenceTimestamp(ciEvidence.generatedAt);
  if (!ciEvidenceGeneratedAt) {
    failures.push("CI_EVIDENCE_FILE generatedAt must be a valid timestamp");
  }
  if (ciEvidence.checkRun?.name !== "Verify product gates") {
    failures.push("CI_EVIDENCE_FILE checkRun.name must be Verify product gates");
  }
  if (ciEvidence.checkRun?.status !== "completed" || ciEvidence.checkRun?.conclusion !== "success") {
    failures.push("CI_EVIDENCE_FILE checkRun must be completed with conclusion=success");
  }
  validateCiCheckRunTimestamps(ciEvidence, ciEvidenceGeneratedAt);
}

const evaluationSetEvidence = readJsonEvidence(evaluationSetEvidenceFile, "EVALUATION_SET_EVIDENCE_FILE");
let evaluationSetEvidenceGeneratedAt = null;
if (!evaluationSetEvidenceFile) {
  failures.push("EVALUATION_SET_EVIDENCE_FILE is required and must be generated by npm run eval:set for the latest PR head");
} else if (evaluationSetEvidence) {
  if (evaluationSetEvidence.schemaVersion !== "evaluation-set-evidence/v1") {
    failures.push("EVALUATION_SET_EVIDENCE_FILE schemaVersion must be evaluation-set-evidence/v1");
  }
  if (evaluationSetEvidence.prHeadSha !== prHeadSha) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE prHeadSha must match PR_HEAD_SHA");
  }
  evaluationSetEvidenceGeneratedAt = parseEvidenceTimestamp(evaluationSetEvidence.generatedAt);
  if (!evaluationSetEvidenceGeneratedAt) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE generatedAt must be a valid timestamp");
  }
  validateEvaluationSetEvidence(evaluationSetEvidence);
}

if (requireOpenAI && process.env.REQUIRE_OPENAI !== "true") {
  failures.push("REQUIRE_OPENAI=true must be recorded for production release verification");
}

if (requireTeacherToken && process.env.REQUIRE_TEACHER_TOKEN !== "true") {
  failures.push("REQUIRE_TEACHER_TOKEN=true must be recorded for production release verification");
}

if (requireClassroomConfig && process.env.REQUIRE_CLASSROOM_CONFIG !== "true") {
  failures.push("REQUIRE_CLASSROOM_CONFIG=true must be recorded for filming release verification");
}

if (requireCloudflareEdge && process.env.REQUIRE_CLOUDFLARE_EDGE !== "true") {
  failures.push("REQUIRE_CLOUDFLARE_EDGE=true must be recorded for production Cloudflare release verification");
}

const externalReview = readJsonEvidence(externalReviewFile, "EXTERNAL_REVIEW_FILE");
let externalReviewGeneratedAt = null;
if (!externalReviewFile) {
  failures.push("EXTERNAL_REVIEW_FILE is required and must contain the external GPT-5.5 xhigh/equivalent review decision");
} else if (externalReview) {
  if (externalReview.schemaVersion !== "external-review-evidence/v1") {
    failures.push("EXTERNAL_REVIEW_FILE schemaVersion must be external-review-evidence/v1 generated by npm run review:evidence");
  }
  if (normalizeDecision(externalReview.decision || externalReview.reviewDecision) !== "approve") {
    failures.push("EXTERNAL_REVIEW_FILE decision must be APPROVE");
  }
  if (!externalReview.prHeadSha || externalReview.prHeadSha !== prHeadSha) {
    failures.push("EXTERNAL_REVIEW_FILE prHeadSha must match PR_HEAD_SHA");
  }
  externalReviewGeneratedAt = parseEvidenceTimestamp(externalReview.generatedAt);
  if (!externalReviewGeneratedAt) {
    failures.push("EXTERNAL_REVIEW_FILE generatedAt must be a valid timestamp");
  }
  if (!String(externalReview.reviewer || externalReview.model || "").trim()) {
    failures.push("EXTERNAL_REVIEW_FILE must identify the external reviewer/model");
  }
  if (!isValidExternalReviewSource(externalReview.source)) {
    failures.push("EXTERNAL_REVIEW_FILE source must include an https review URL or transcriptSha256 from EXTERNAL_REVIEW_TRANSCRIPT_FILE");
  }
  for (const [label, value] of [
    ["ciStatus", externalReview.evidenceChecked?.ciStatus],
    ["testsStatus", externalReview.evidenceChecked?.testsStatus],
    ["evalStatus", externalReview.evidenceChecked?.evalStatus],
    ["readinessStatus", externalReview.evidenceChecked?.readinessStatus],
    ["smokeStatus", externalReview.evidenceChecked?.smokeStatus],
    ["verifyDeployStatus", externalReview.evidenceChecked?.verifyDeployStatus],
    ["classroomConfigStatus", externalReview.evidenceChecked?.classroomConfigStatus]
  ]) {
    if (!isPassStatus(value)) {
      failures.push(`EXTERNAL_REVIEW_FILE evidenceChecked.${label} must be pass or success`);
    }
  }
  if (Array.isArray(externalReview.blockingFindings) && externalReview.blockingFindings.length > 0) {
    failures.push("EXTERNAL_REVIEW_FILE cannot include blockingFindings when decision is APPROVE");
  }
  if (requireClassroomChatProof && externalReview.requireClassroomChatProof !== true) {
    failures.push("EXTERNAL_REVIEW_FILE must be generated with REQUIRE_CLASSROOM_CHAT_PROOF=true");
  }
  validateExternalReviewArtifacts(externalReview.evidenceArtifacts);
}

const deployEvidence = readJsonEvidence(verifyDeployEvidenceFile, "VERIFY_DEPLOY_EVIDENCE_FILE");
let deployEvidenceGeneratedAt = null;
if (!verifyDeployEvidenceFile) {
  failures.push("VERIFY_DEPLOY_EVIDENCE_FILE is required and must be generated by npm run verify:deploy against the real Worker URL");
} else if (deployEvidence) {
  if (deployEvidence.schemaVersion !== "deploy-verification-evidence/v1") {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE schemaVersion must be deploy-verification-evidence/v1");
  }
  if (normalizeStatus(deployEvidence.status) !== "pass") {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE status must be pass");
  }
  if (!deployEvidence.prHeadSha || deployEvidence.prHeadSha !== prHeadSha) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE prHeadSha must match PR_HEAD_SHA");
  }
  deployEvidenceGeneratedAt = parseEvidenceTimestamp(deployEvidence.generatedAt);
  if (!deployEvidenceGeneratedAt) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE generatedAt must be a valid timestamp");
  }
  if (normalizeBaseUrl(deployEvidence.workerUrl) !== normalizeBaseUrl(workerUrl)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE workerUrl must match WORKER_URL");
  }
  if (deployEvidence.requireOpenAI !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record requireOpenAI=true");
  }
  if (deployEvidence.requireTeacherToken !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record requireTeacherToken=true");
  }
  if (requireCloudflareEdge && deployEvidence.requireCloudflareEdge !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record requireCloudflareEdge=true");
  }
  if (requireCloudflareEdge && deployEvidence.cloudflareEdge?.present !== true) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must prove Cloudflare edge headers were present");
  }
  if (requireCloudflareEdge && !hasCloudflareEdgeHeaderEvidence(deployEvidence.cloudflareEdge?.headers)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE cloudflareEdge.headers must include Cloudflare response header evidence");
  }
  if (!hasValidDeployHealthEvidence(deployEvidence.health)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must include a sanitized /api/health evidence snapshot");
  }
  if (!isSafeDeployVerifyRoom(deployEvidence.verifyRoom)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE verifyRoom must be a deploy verification room, not a filming room");
  }
  if (!hasValidSharingUrls(deployEvidence.sharingUrls, deployEvidence.verifyRoom, workerUrl)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must include student/teacher sharing URL evidence with no student token");
  }
  if (!String(deployEvidence.expectedOpenAIModel || "").trim()) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record expectedOpenAIModel");
  } else if (deployEvidence.health?.openaiModel !== deployEvidence.expectedOpenAIModel) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE health.openaiModel must match expectedOpenAIModel");
  }
  if (!Number.isFinite(deployEvidence.expectedOpenAITimeoutMs)) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must record expectedOpenAITimeoutMs");
  } else if (deployEvidence.health?.openaiTimeoutMs !== deployEvidence.expectedOpenAITimeoutMs) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE health.openaiTimeoutMs must match expectedOpenAITimeoutMs");
  }
  if (!Number.isFinite(deployEvidence.totalChecks) || deployEvidence.totalChecks < 18) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE must include all deploy verification checks");
  }
  if (deployEvidence.passedChecks !== deployEvidence.totalChecks) {
    failures.push("VERIFY_DEPLOY_EVIDENCE_FILE passedChecks must equal totalChecks");
  }
}

if (requireClassroomConfig && classroomConfigEvidenceFiles.length === 0) {
  failures.push("CLASSROOM_CONFIG_EVIDENCE_FILES or CLASSROOM_CONFIG_EVIDENCE_FILE is required and must be generated by npm run rehearsal:config against every filming room");
} else if (classroomConfigEvidenceFiles.length) {
  const seenRooms = new Set();
  for (const file of classroomConfigEvidenceFiles) {
    const classroomConfigEvidence = readJsonEvidence(file, "CLASSROOM_CONFIG_EVIDENCE_FILE");
    if (!classroomConfigEvidence) continue;
    validateClassroomConfigEvidence(classroomConfigEvidence, file, seenRooms, externalReviewGeneratedAt);
  }
  if (requireClassroomConfig) validateExpectedClassroomRooms(seenRooms);
}

if (externalReviewGeneratedAt && deployEvidenceGeneratedAt && externalReviewGeneratedAt < deployEvidenceGeneratedAt) {
  failures.push("EXTERNAL_REVIEW_FILE generatedAt must be after VERIFY_DEPLOY_EVIDENCE_FILE generatedAt");
}

if (externalReviewGeneratedAt && ciEvidenceGeneratedAt && externalReviewGeneratedAt < ciEvidenceGeneratedAt) {
  failures.push("EXTERNAL_REVIEW_FILE generatedAt must be after CI_EVIDENCE_FILE generatedAt");
}

if (externalReviewGeneratedAt && evaluationSetEvidenceGeneratedAt && externalReviewGeneratedAt < evaluationSetEvidenceGeneratedAt) {
  failures.push("EXTERNAL_REVIEW_FILE generatedAt must be after EVALUATION_SET_EVIDENCE_FILE generatedAt");
}

if (failures.length) {
  for (const failure of failures) console.error(`FAIL ${failure}`);
  console.error(`release audit failed: ${failures.length} issue(s)`);
  process.exit(1);
}

console.log("release audit passed");
console.log(`prHeadSha=${prHeadSha}`);
console.log(`ciHeadSha=${ciHeadSha}`);
console.log(`workerUrl=${workerUrl}`);
console.log(`externalReviewDecision=${externalReviewDecision}`);
console.log(`verifyDeployStatus=${verifyDeployStatus}`);
console.log(`externalReviewFile=${externalReviewFile}`);
console.log(`ciEvidenceFile=${ciEvidenceFile}`);
console.log(`evaluationSetEvidenceFile=${evaluationSetEvidenceFile}`);
console.log(`verifyDeployEvidenceFile=${verifyDeployEvidenceFile}`);
console.log(`classroomConfigEvidenceFiles=${classroomConfigEvidenceFiles.join(",")}`);
console.log(`expectedClassroomRooms=${expectedClassroomRooms.join(",")}`);

function normalizeDecision(value) {
  return String(value || "").trim().toLowerCase().replace(/[^a-z_]/g, "");
}

function normalizeStatus(value) {
  return String(value || "").trim().toLowerCase();
}

function isPassStatus(value) {
  const status = normalizeStatus(value);
  return status === "pass" || status === "success";
}

function isHttpsUrl(value) {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && Boolean(url.hostname);
  } catch {
    return false;
  }
}

function isValidExternalReviewSource(source) {
  if (!source || typeof source !== "object") return false;
  if (source.url && isHttpsUrl(source.url)) return true;
  if (typeof source.transcriptSha256 === "string" && /^[a-f0-9]{64}$/.test(source.transcriptSha256) && Number(source.transcriptBytes) > 0) return true;
  return false;
}

function validateExternalReviewArtifacts(artifacts) {
  if (!artifacts || typeof artifacts !== "object") {
    failures.push("EXTERNAL_REVIEW_FILE evidenceArtifacts must bind the review to CI, deploy, and classroom evidence files");
    return;
  }
  validateEvidenceArtifact(
    artifacts.ci,
    ciEvidenceFile,
    "EXTERNAL_REVIEW_FILE evidenceArtifacts.ci"
  );
  validateEvidenceArtifact(
    artifacts.evaluationSet,
    evaluationSetEvidenceFile,
    "EXTERNAL_REVIEW_FILE evidenceArtifacts.evaluationSet"
  );
  validateEvidenceArtifact(
    artifacts.deployVerification,
    verifyDeployEvidenceFile,
    "EXTERNAL_REVIEW_FILE evidenceArtifacts.deployVerification"
  );
  const classroomArtifacts = Array.isArray(artifacts.classroomConfigs) ? artifacts.classroomConfigs : [];
  if (classroomArtifacts.length !== classroomConfigEvidenceFiles.length) {
    failures.push("EXTERNAL_REVIEW_FILE evidenceArtifacts.classroomConfigs must include every CLASSROOM_CONFIG_EVIDENCE_FILES entry");
  }
  for (const file of classroomConfigEvidenceFiles) {
    const artifact = classroomArtifacts.find((item) => item?.file === file);
    validateEvidenceArtifact(
      artifact,
      file,
      `EXTERNAL_REVIEW_FILE evidenceArtifacts.classroomConfigs ${file}`
    );
  }
}

function validateEvaluationSetEvidence(evidence) {
  if (evidence.totalTurns !== 50) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE totalTurns must be 50");
  }
  if (evidence.teacherAuditIncluded !== true) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE must include teacher audit fields");
  }
  if (evidence.pressureTurnCount !== 10) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE pressureTurnCount must be 10");
  }
  if (evidence.publicProjection?.exposesTeacherAudit !== false) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE publicProjection must not expose teacher audit fields");
  }
  if (!Array.isArray(evidence.teacherReviewItems) || evidence.teacherReviewItems.length !== 50) {
    failures.push("EVALUATION_SET_EVIDENCE_FILE teacherReviewItems must contain 50 turns");
  }
  for (const level of ["1", "2", "3", "4"]) {
    const bucket = evidence.byLevel?.[level];
    if (!bucket || !Number.isFinite(bucket.total) || bucket.total <= 0 || bucket.passedPreflight !== bucket.total) {
      failures.push(`EVALUATION_SET_EVIDENCE_FILE byLevel.${level} must have all turns passing preflight`);
    }
  }
}

function validateEvidenceArtifact(artifact, file, label) {
  if (!file) return;
  if (!artifact || typeof artifact !== "object") {
    failures.push(`${label} is required`);
    return;
  }
  if (artifact.file !== file) {
    failures.push(`${label}.file must match ${file}`);
  }
  if (!/^[a-f0-9]{64}$/.test(String(artifact.sha256 || ""))) {
    failures.push(`${label}.sha256 must be a SHA-256 digest`);
    return;
  }
  const currentSha256 = hashEvidenceFile(file, label);
  if (currentSha256 && artifact.sha256 !== currentSha256) {
    failures.push(`${label}.sha256 must match the current evidence file`);
  }
}

function hashEvidenceFile(file, label) {
  try {
    return createHash("sha256").update(readFileSync(file)).digest("hex");
  } catch (error) {
    failures.push(`${label} referenced file must be readable: ${error instanceof Error ? error.message : String(error)}`);
    return null;
  }
}

function hasCloudflareEdgeHeaderEvidence(headers) {
  if (!headers || typeof headers !== "object") return false;
  const values = [
    headers.cfRay,
    headers.cfCacheStatus,
    headers.server,
    headers.reportTo
  ].map((value) => String(value || "").toLowerCase());
  return Boolean(values[0]) || values.some((value) => value.includes("cloudflare"));
}

function hasValidDeployHealthEvidence(health) {
  if (!health || typeof health !== "object") return false;
  if (Number(health.status) !== 200) return false;
  if (health.ok !== true) return false;
  if (requireOpenAI && health.provider !== "openai") return false;
  if (requireOpenAI && health.openaiConfigured !== true) return false;
  if (requireTeacherToken && health.teacherProtected !== true) return false;
  if (typeof health.openaiModel !== "string") return false;
  if (!Number.isFinite(health.openaiTimeoutMs)) return false;
  return JSON.stringify(health).includes("OPENAI_API_KEY") === false;
}

function normalizeBaseUrl(value) {
  try {
    const url = new URL(String(value || ""));
    url.pathname = "/";
    url.search = "";
    url.hash = "";
    return url.toString();
  } catch {
    return "";
  }
}

function readJsonEvidence(file, label) {
  if (!file) return null;
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    failures.push(`${label} must be readable JSON: ${error instanceof Error ? error.message : String(error)}`);
    return null;
  }
}

function parseEvidenceFileList(value) {
  return String(value || "")
    .split(/[\n,]+/)
    .map((file) => file.trim())
    .filter(Boolean);
}

function validateClassroomConfigEvidence(classroomConfigEvidence, file, seenRooms, reviewGeneratedAt) {
  const label = `CLASSROOM_CONFIG_EVIDENCE_FILE ${file}`;
  const classroomGeneratedAt = parseEvidenceTimestamp(classroomConfigEvidence.generatedAt);
  if (classroomConfigEvidence.schemaVersion !== "classroom-config-evidence/v1") {
    failures.push(`${label} schemaVersion must be classroom-config-evidence/v1`);
  }
  if (!classroomGeneratedAt) {
    failures.push(`${label} generatedAt must be a valid timestamp`);
  }
  if (reviewGeneratedAt && classroomGeneratedAt && reviewGeneratedAt < classroomGeneratedAt) {
    failures.push(`EXTERNAL_REVIEW_FILE generatedAt must be after ${label} generatedAt`);
  }
  if (normalizeStatus(classroomConfigEvidence.status) !== "pass") {
    failures.push(`${label} status must be pass`);
  }
  if (!classroomConfigEvidence.prHeadSha || classroomConfigEvidence.prHeadSha !== prHeadSha) {
    failures.push(`${label} prHeadSha must match PR_HEAD_SHA`);
  }
  if (normalizeBaseUrl(classroomConfigEvidence.workerUrl) !== normalizeBaseUrl(workerUrl)) {
    failures.push(`${label} workerUrl must match WORKER_URL`);
  }
  if (!isFilmingRoom(classroomConfigEvidence.roomId)) {
    failures.push(`${label} roomId must be a filming/rehearsal room, not default-classroom or deploy-verify`);
  } else if (seenRooms.has(classroomConfigEvidence.roomId)) {
    failures.push(`${label} roomId must be unique across CLASSROOM_CONFIG_EVIDENCE_FILES`);
  } else {
    seenRooms.add(classroomConfigEvidence.roomId);
  }
  if (!Number.isInteger(classroomConfigEvidence.expectedLevel) || classroomConfigEvidence.expectedLevel < 1 || classroomConfigEvidence.expectedLevel > 4) {
    failures.push(`${label} expectedLevel must be 1, 2, 3, or 4`);
  }
  if (!String(classroomConfigEvidence.expectedPersona || "").trim()) {
    failures.push(`${label} expectedPersona is required`);
  }
  if (classroomConfigEvidence.requireOpenAI !== true) {
    failures.push(`${label} must record requireOpenAI=true`);
  }
  if (classroomConfigEvidence.requireTeacherToken !== true) {
    failures.push(`${label} must record requireTeacherToken=true`);
  }
  if (!hasValidClassroomHealthEvidence(classroomConfigEvidence.observedHealth)) {
    failures.push(`${label} must include a sanitized /api/health evidence snapshot`);
  }
  if (!String(classroomConfigEvidence.expectedOpenAIModel || "").trim()) {
    failures.push(`${label} must record expectedOpenAIModel`);
  } else if (classroomConfigEvidence.observedHealth?.openaiModel !== classroomConfigEvidence.expectedOpenAIModel) {
    failures.push(`${label} observedHealth.openaiModel must match expectedOpenAIModel`);
  }
  if (!Number.isFinite(classroomConfigEvidence.expectedOpenAITimeoutMs)) {
    failures.push(`${label} must record expectedOpenAITimeoutMs`);
  } else if (classroomConfigEvidence.observedHealth?.openaiTimeoutMs !== classroomConfigEvidence.expectedOpenAITimeoutMs) {
    failures.push(`${label} observedHealth.openaiTimeoutMs must match expectedOpenAITimeoutMs`);
  }
  if (classroomConfigEvidence.observedConfig?.persona !== classroomConfigEvidence.expectedPersona ||
    Number(classroomConfigEvidence.observedConfig?.level) !== classroomConfigEvidence.expectedLevel) {
    failures.push(`${label} observedConfig must match expected Level/persona`);
  }
  if (!hasValidSharingUrls(classroomConfigEvidence.sharingUrls, classroomConfigEvidence.roomId, workerUrl)) {
    failures.push(`${label} must include student/teacher sharing URL evidence with no student token`);
  }
  if (!Array.isArray(classroomConfigEvidence.checks) || classroomConfigEvidence.checks.some((check) => check?.passed !== true)) {
    failures.push(`${label} checks must all pass`);
  }
  if (requireClassroomChatProof && classroomConfigEvidence.verifyClassroomChat !== true) {
    failures.push(`${label} must record verifyClassroomChat=true when REQUIRE_CLASSROOM_CHAT_PROOF=true`);
  }
  if (classroomConfigEvidence.verifyClassroomChat === true &&
    !hasValidSampleClassroomChat(classroomConfigEvidence.sampleChat, classroomConfigEvidence.expectedLevel, classroomConfigEvidence.expectedPersona)) {
    failures.push(`${label} sampleChat must prove /api/chat audit used expected Level/persona`);
  }
}

function validateCiCheckRunTimestamps(ciEvidence, ciGeneratedAt) {
  const startedAt = parseEvidenceTimestamp(ciEvidence.checkRun?.startedAt);
  const completedAt = parseEvidenceTimestamp(ciEvidence.checkRun?.completedAt);
  if (!startedAt) {
    failures.push("CI_EVIDENCE_FILE checkRun.startedAt must be a valid timestamp");
  }
  if (!completedAt) {
    failures.push("CI_EVIDENCE_FILE checkRun.completedAt must be a valid timestamp");
  }
  if (startedAt && completedAt && completedAt < startedAt) {
    failures.push("CI_EVIDENCE_FILE checkRun.completedAt must be after checkRun.startedAt");
  }
  if (ciGeneratedAt && completedAt && ciGeneratedAt < completedAt) {
    failures.push("CI_EVIDENCE_FILE generatedAt must be after checkRun.completedAt");
  }
}

function parseEvidenceTimestamp(value) {
  const timestamp = Date.parse(String(value || ""));
  return Number.isFinite(timestamp) ? timestamp : null;
}

function validateExpectedClassroomRooms(seenRooms) {
  if (expectedClassroomRooms.length === 0) {
    failures.push("EXPECTED_CLASSROOM_ROOMS is required when REQUIRE_CLASSROOM_CONFIG=true so release audit can prove every filming room has evidence");
    return;
  }
  const expectedRooms = new Set(expectedClassroomRooms.map((room) => normalizeEvidenceRoom(room)));
  for (const room of expectedRooms) {
    if (!isFilmingRoom(room)) {
      failures.push(`EXPECTED_CLASSROOM_ROOMS contains non-filming room ${room}`);
    }
    if (!seenRooms.has(room)) {
      failures.push(`CLASSROOM_CONFIG_EVIDENCE_FILES missing expected filming room ${room}`);
    }
  }
  for (const room of seenRooms) {
    if (!expectedRooms.has(room)) {
      failures.push(`CLASSROOM_CONFIG_EVIDENCE_FILES contains unexpected filming room ${room}`);
    }
  }
}

function normalizeEvidenceRoom(value) {
  return String(value || "").trim();
}

function hasValidClassroomHealthEvidence(health) {
  if (!health || typeof health !== "object") return false;
  if (Number(health.status) !== 200) return false;
  if (health.ok !== true) return false;
  if (requireOpenAI && health.openaiConfigured !== true) return false;
  if (requireTeacherToken && health.teacherProtected !== true) return false;
  if (typeof health.openaiModel !== "string") return false;
  if (health.openaiTimeoutMs !== null && !Number.isFinite(health.openaiTimeoutMs)) return false;
  return JSON.stringify(health).includes("OPENAI_API_KEY") === false;
}

function hasValidSharingUrls(sharingUrls, roomId, expectedWorkerUrl) {
  if (!sharingUrls || typeof sharingUrls !== "object") return false;
  if (sharingUrls.studentUrlHasToken !== false) return false;
  if (sharingUrls.teacherUrlRequiresToken !== true) return false;
  if (JSON.stringify(sharingUrls).includes("TEACHER_TOKEN=")) return false;
  let studentUrl;
  let teacherUrl;
  try {
    studentUrl = new URL(sharingUrls.studentUrl);
    teacherUrl = new URL(sharingUrls.teacherUrlTemplate);
  } catch {
    return false;
  }
  if (normalizeBaseUrl(studentUrl.toString()) !== normalizeBaseUrl(expectedWorkerUrl)) return false;
  if (normalizeBaseUrl(teacherUrl.toString()) !== normalizeBaseUrl(expectedWorkerUrl)) return false;
  if (studentUrl.pathname !== "/") return false;
  if (teacherUrl.pathname !== "/teacher") return false;
  if (studentUrl.searchParams.get("room") !== roomId) return false;
  if (teacherUrl.searchParams.get("room") !== roomId) return false;
  if (studentUrl.searchParams.has("token")) return false;
  return teacherUrl.searchParams.get("token") === "<TEACHER_TOKEN>";
}

function hasValidClassroomSharingUrls(sharingUrls, roomId, expectedWorkerUrl) {
  return hasValidSharingUrls(sharingUrls, roomId, expectedWorkerUrl);
}

function hasValidSampleClassroomChat(sampleChat, expectedLevel, expectedPersona) {
  if (!sampleChat || typeof sampleChat !== "object") return false;
  if (!String(sampleChat.sessionId || "").startsWith("classroom-config-")) return false;
  if (!Number.isFinite(sampleChat.studentVisibleAnswerLength) || sampleChat.studentVisibleAnswerLength <= 0) return false;
  if (sampleChat.auditInput?.appliedLevel !== expectedLevel) return false;
  if (sampleChat.auditInput?.persona !== expectedPersona) return false;
  if (typeof sampleChat.preflightVerdict !== "string" || !sampleChat.preflightVerdict) return false;
  return sampleChat.debriefRequired === true;
}

function isFilmingRoom(value) {
  const room = String(value || "").trim();
  return Boolean(room) &&
    room !== "default-classroom" &&
    room !== "deploy-verify" &&
    !room.startsWith("deploy-verify-");
}

function isSafeDeployVerifyRoom(value) {
  const room = String(value || "").trim();
  return room === "deploy-verify" || room.startsWith("deploy-verify-");
}
